add inline ads feature
superdesk/web-publisher pull request #1165
Opened 2020-11-05 12:03 UTC by mehdignu

Fixes #
(comma separated list of tickets/issues/bugs fixed by the PR)

## Proposed Changes

For the ad integration on articles we need a dynamic functionality. The ad integration should be depending on paragraphs and the numbers of characters.

The following rules should be respected:

- an adslots should be integrated after every paragraph (with 200 characters)
- an paragraph should have at least 200 characters
- an adslot should only be integrated if another paragraph follows
- no integration before and after one single paragraph
- a item of a list could be a paragraph if it has more than 200 characters
- no integration before a list
- no integration after headlines
- the number of characters should be adjustable in den backend
- has a paragraph less than 200 characters the next paragraph(s) should be added till the numbers of 200 characters is reached

License: AGPLv3

2020-11-05 19:26 UTC, ahilles107 commented on src/SWP/Bundle/CoreBundle/Twig/ArticleBodyExtension.php
> +        $paragraphChars = $_ENV['ADS_CHARACTERS'];
You can't do this like that. Publisher (and symfony) have other way for accessing env variables. It should be passed to service via DI.

2020-11-05 19:27 UTC, ahilles107 commented
where we can find tests?

2020-12-08 12:42 UTC, takeit requested changes
@mehdignu please see my comments and we are ready to merge. The PR LGTM.

2020-12-08 12:42 UTC, takeit commented on .env
> +# after how many charachters in the body's paragraph the ad should to be placed
there is a typo in `charachters`

2020-12-08 12:42 UTC, takeit commented on src/SWP/Bundle/CoreBundle/Tests/Twig/InlineAdsTest.php
> +    public function setUp()
please add `:void` return type to all the functions in this class and `declare(strict_types=1);` after `<?php`

2024-02-29 15:52 UTC, closed without merging